name: Build

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            artifact-name: Windows
            target: ALL_BUILD
          - os: ubuntu-22.04
            artifact-name: Linux
            target: all
          - os: macOS-11
            artifact-name: macOS
            target: all

    name: "${{ matrix.artifact-name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: ilammy/msvc-dev-cmd@v1.12.0
        if: matrix.artifact-name == 'Windows'

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: latest
        if: matrix.artifact-name == 'Windows'

      - name: configure
        run: cmake -B build -S .

      - name: build
        run: cmake --build build --target ${{ matrix.target }} --config RelWithDebInfo --parallel $(nproc)

      # Crashes with exit code 0xc0000135 on Windows (missing DLLs)
      - name: test
        working-directory: build
        run: ctest -R SleipnirTest -C RelWithDebInfo --output-on-failure
        if: matrix.artifact-name != 'Windows'

      - name: install
        run: cmake --install build --config RelWithDebInfo --prefix pkg

      - uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ matrix.artifact-name }}
          path: pkg
